#!/usr/bin/env sh

#load scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

## Default to managed windows
yabai -m config layout bsp

## Set the spacebar to the top
# SPACEBAR_HEIGHT=$(spacebar -m config height)
# SPACEBAR_HEIGHT=$(sketchybar --query bar | jq  .height)
SPACEBAR_HEIGHT= $(($(sketchybar --query bar | jq  .height ) + 5))
yabai -m config external_bar all:0:$SPACEBAR_HEIGHT


#window_border
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff51425C
yabai -m config insert_window_border_color   0xff8E83B8
  # normal_window_border_color        \


yabai -m config normal_window_opacity        1.0

# floating windows
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^Calculator$" manage=off

#turn off window shadows
yabai -m config window_shadow off

#window gap
yabai -m config top_padding    20
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

function setup_space {
  local idx="$1"
  local name="$2"
  local layout="$3"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
  yabai -m config --space "$idx" layout "$layout"
}

setup_space 1 free   bsp 
setup_space 2 code   stack 
setup_space 3 web    stack 
setup_space 4 social stack
setup_space 5 media  stack
setup_space 6 utils  stack
setup_space 7 other  bsp
setup_space 8 zoom  stack

# move some apps automatically to specific spaces, if space is labeled must use label name
# Code Space
yabai -m rule --add app="^iTerm2$"             space=code
yabai -m rule --add app="^Visual Studio Code$" space=code
yabai -m rule --add app="^Code$"              space=code
yabai -m rule --add app="^Cursor$"              space=code
# Web Space
yabai -m rule --add app="^Firefox$"            space=web
yabai -m rule --add app="^Google Chrome$"      space=web
yabai -m rule --add app="^Brave$"              space=web
# Social Space
yabai -m rule --add app="^WhatsApp$"           space=social
yabai -m rule --add app="WhatsApp$"            space=social
yabai -m rule --add app="^Slack$"              space=social
yabai -m rule --add app="^Discord$"            space=social

# Media Space
yabai -m rule --add app="^Spotify$"           space=media
# Utils Space
yabai -m rule --add app="^pgAdmin$"           space=utils
yabai -m rule --add app="^pgAdmin 4$"         space=utils
yabai -m rule --add app="^WireGuard$"         space=utils

yabai -m rule --add app="^Postman$"           space=utils
yabai -m rule --add app="^Docker$"            space=utils
yabai -m rule --add app="^1Password$"         space=utils
yabai -m rule --add app="^1Password 7$"       space=utils
yabai -m rule --add app="^Notes$"             space=utils

## Put zoom in its own space
yabai -m rule --add app="^Zoom$"              space=zoom


## Remove Extra Spaces on start up
for idx in $(yabai -m query --spaces | jq '.[].index | select(. > 6)' | sort -nr); do
  yabai -m space --destroy "$idx"
done


##  Adjust the padding based on display
yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/set_padding.py"
yabai -m signal --add event=window_focused action="python3 ~/.config/yabai/set_padding.py"
yabai -m signal --add event=window_created action="python3 ~/.config/yabai/set_padding.py"

## Allows for slack screen sharing
yabai -m config window_border_blur off

echo "yabai configuration loaded.."


# Log Files
# /opt/homebrew/var/log/yabai/yabai.out.log
# /opt/homebrew/var/log/yabai/yabai.err.log
